### PR TITLE
(fix) Further improvements to alsa device detection...

### PR DESCRIPTION
**Pull request by ethoms**
Fix detection of already open devices.

My last changes to the alsa card detection in the function 'alsa_card_detect' was using the "plughw:<card_id>,<device_id>" (e.g: "plughw:0,0) device name syntax. This will not open a device to check capabilities if that device is currently open by another application. By using the device names convention as follows; "plug:device_name:card_name" (e.g: "plug:default:PCH") the card can be opened and capabilities checked.

Tested with Linphone 3.9.1. Audio device detection and stored preferences are more stable now.

NOTE: I have not tested these changes on the master branch against the latest Linphone tree. The code change is isolated within one function whereby the inputs and outputs are the same. So I am confident it will not have any incompatabilty witgh recent changes elsewhere. However, I would like to test it, if somebody can point me to instructions on how to build the latest stuff from a local git repo.

### CODE REVIEW

**Comment by bagage** [comment]
Sure @ethoms, and thanks for your work here! To compile, the most simple solution I believe is to use [linphone-desktop](https://github.com/BelledonneCommunications/linphone-desktop). Basically:

```
git clone https://github.com/BelledonneCommunications/linphone-desktop --recursive
./prepare.py
make
./OUTPUT/bin/Linphone
```

It may takes some time but that's the safest way to build Linphone. If you have any trouble with that procedure (I hope not!), please tell me.

**Comment by ethoms** [comment]
Thanks bagage. I used your instructions and initially prepare.py failed saying that cmake must be v3.0 or above, Slackware 14.1 is using cmake 2.8.x. So I installed cmake 3.5 from Slackware current. Then prepare.py suceeded.

However 'make' fails with the following:
```
make[6]: Entering directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
[  0%] Building C object /home/conspec/LocalDev/linphone-desktop/WORK/Build/bctoolbox/src/CMakeFiles/bctoolbox.dir/utils/port.c.o
[  0%] Building C object /home/conspec/LocalDev/linphone-desktop/WORK/Build/bctoolbox/src/CMakeFiles/bctoolbox.dir/logging/logging.c.o
[  0%] Building C object /home/conspec/LocalDev/linphone-desktop/WORK/Build/bctoolbox/src/CMakeFiles/bctoolbox.dir/containers/list.c.o
[  0%] Building C object /home/conspec/LocalDev/linphone-desktop/WORK/Build/bctoolbox/src/CMakeFiles/bctoolbox.dir/crypto/mbedtls.c.o
[  1%] Building CXX object /home/conspec/LocalDev/linphone-desktop/WORK/Build/bctoolbox/src/CMakeFiles/bctoolbox.dir/containers/map.cc.o
[  1%] Linking CXX shared library libbctoolbox.so
make[6]: Leaving directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
[  1%] Built target bctoolbox
make[6]: Entering directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
Scanning dependencies of target bctoolbox_tester
make[6]: Leaving directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
make[6]: Entering directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
[  1%] Building C object /home/conspec/LocalDev/linphone-desktop/WORK/Build/bctoolbox/tester/CMakeFiles/bctoolbox_tester.dir/bctoolbox_tester.c.o
[  2%] Building CXX object /home/conspec/LocalDev/linphone-desktop/WORK/Build/bctoolbox/tester/CMakeFiles/bctoolbox_tester.dir/containers.cc.o
[  2%] Linking CXX executable bctoolbox_tester
make[6]: Leaving directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
[  2%] Built target bctoolbox_tester
make[6]: Entering directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
[  2%] Generating grammars/belle_sip_messageLexer.c, grammars/belle_sip_messageLexer.h, grammars/belle_sip_messageParser.c, grammars/belle_sip_messageParser.h
/bin/sh: /usr/include/antlr3: Is a directory
make[6]: *** [/home/conspec/LocalDev/linphone-desktop/WORK/Build/bellesip/src/grammars/belle_sip_messageLexer.c] Error 126
make[6]: Leaving directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
make[5]: *** [/home/conspec/LocalDev/linphone-desktop/WORK/Build/bellesip/src/CMakeFiles/bellesip.dir/all] Error 2
make[5]: Leaving directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/conspec/LocalDev/linphone-desktop/WORK/Build/linphone_builder'
make[3]: *** [/home/conspec/LocalDev/linphone-desktop/WORK/Stamp/EP_linphone_builder/EP_linphone_builder-build] Error 2
make[3]: Leaving directory `/home/conspec/LocalDev/linphone-desktop/WORK/cmake'
make[2]: *** [CMakeFiles/EP_linphone_builder.dir/all] Error 2
make[2]: Leaving directory `/home/conspec/LocalDev/linphone-desktop/WORK/cmake'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/conspec/LocalDev/linphone-desktop/WORK/cmake'
make: *** [all] Error 2
```

I have libantlr3c installed, it's version 3.4 and builds Linphone 3.9.1 just fine from the tarball.

**Comment by bagage** [comment]
Did you run `./prepare.py` with no option? Could you run `make -j1` instead of `make` please?

**Comment by ethoms** [comment]
It's OK, I fixed it by uninstalling libantlr3c. Looks like it built OK now. I guess it likes to use it's own antlr3 instead of a prior system installed version.

Now I just need to apply my changes and test. Is there a git way to do that? Otherwise I'll just do it manually.

**Comment by bagage** [comment]
Git is design for that ;). Basically you want to use your own mediastreamer2 copy so you should do:
```
cd submodules/linphone/mediastreamer2
git remote add ethoms https://github.com/ethoms/mediastreamer2
git fetch ethoms
git checkout ethoms/fix-alsa-device-detect
```
Then go back and recompile:
```
cd -
make
```
You may want to execute automatic tests to check that there are no regressions:
```
./WORK/Build/ms2/tester/mediastreamer2_tester --resource-dir submodules/linphone/mediastreamer2/tester
```

**Comment by ethoms** [comment]
Thanks for th git tips, very useful to know. Actually I already tesed by manually replacing alsa.c with my copy. It worked fine. I'm just building again after using git to checkout my branch. Will report back in a few minutes.

**Comment by ethoms** [comment]
My changes work fine and all regression tests pass.

```
Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites      8      8    n/a      0        0
               tests     75     75     75      0        0
             asserts    686    686    686      0      n/a

Elapsed time = 472 seconds
```

Feel free to pull if you are happy with my changes.

**Comment by bagage** [comment]
Merged, thanks @ethoms!

**Comment by ethoms** [comment]
Thanks bagege. Any idea when the next version of mediastreamer2 will be released? Most distro packaging use tarballs.

**Comment by bagage** [comment]
I believe a release should be done in the coming weeks @ethoms, this is a long time since previous release...!

**Pull request closed without merging**
